### ISSUE TITLE
Display map labels?

### ISSUE THREAD

**Issue by sudokoko** [nawendt/SPCartopy#2]
Is there a way to display the categorical labels for each of the geometries, similar to how it's displayed below? Any help would be appreciated :)

<img width="579" alt="Screen Shot 2023-03-30 at 9 23 43 AM" src="https://user-images.githubusercontent.com/68549366/228850314-5e40ef64-6e07-4838-9bf1-13a18627596f.png">

**Comment by nawendt** [comment]
I don't have anything to do that automatically at this point. The geoJSONs do not contain the coordinates for where a forecaster manually places the label, which would also make things pretty simple. I have an idea of how to accomplish this, but I will need to think on it and do some testing.

**Comment by sudokoko** [comment]
Alright, sounds good. Thanks :)

**Comment by sudokoko** [comment]
Also, forgot to mention, are there plans to add MCD plotting? Would be very helpful for my use case.

**Comment by nawendt** [comment]
In terms of the contour labelling, I do not have anything I can do quickly. Probably the best bet would be borrowing from MetPy. They have a little method (which was used to produce your example image) that will try and place labels for arbitrary contours. Check it out [here](https://github.com/Unidata/MetPy/blob/acae7006fccb18f4764135bc21df0c678ad01746/src/metpy/plots/declarative.py#L2202-L2225). It's an undocumented private method, but at least it will help get a position for text labels. From there you just use text plotting methods with proper cartopy transform argument and it should work pretty easy. We will see if I get around to my own contour labelling at some point in the future.

For MDs, that functionality was just added.

**Comment by sudokoko** [comment]
> Probably the best bet would be borrowing from MetPy.

That's what I was going to fall back to. Sounds good!

> For MDs, that functionality was just added.

Awesome! Thanks :)
